export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const HISTORY_CLICK = "HISTORY_CLICK";
export const ACCOUNT_SETTING_CLICK = "ACCOUNT_SETTING_CLICK";
export const OPEN_FEEDBACK = "OPEN_FEEDBACK";
export const CLOSE_FEEDBACK = "CLOSE_FEEDBACK";

// category

export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_COMPLETE_LOADING = "CATEGORY_COMPLETE_LOADING";
export const CATEGORY_EXIST = "CATEGORY_EXIST";
export const SET_CATEGORY_ID = "SET_CATEGORY_ID";

// product

export const NEW_ARRIVAL_SET_LOADING = "NEW_ARRIVAL_SET_LOADING";
export const NEW_ARRIVAL_SET_ERROR = "NEW_ARRIVAL_SET_ERROR";
export const NEW_ARRIVAL_SET_PRODUCT = "NEW_ARRIVAL_SET_PRODUCT";
export const SET_LOADING_ALL_FAVOR_BOOK = "SET_LOADING_ALL_FAVOR_BOOK";
export const SET_ERROR_ALL_FAVOR_BOOK = "SET_ERROR_ALL_FAVOR_BOOK";
export const SET_PRODUCT_ALL_FAVOR_BOOK = "SET_PRODUCT_ALL_FAVOR_BOOK";
export const SET_NEW_ARRIVAL_PAGE = "SET_NEW_ARRIVAL_PAGE";

// single product

export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT_ERROR = "SET_SINGLE_PRODUCT_ERROR";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";

// suggestion product
export const SET_LOADING_SUGGESTION_PRODUCT = "SET_LOADING_SUGGESTION_PRODUCT";
export const SET_SUGGESTION_PRODUCT = "SET_SUGGESTION_PRODUCT";
export const SET_SUGGESTION_PRODUCT_ERROR = "SET_SUGGESTION_PRODUCT_ERROR";

// people looking product
export const SET_LOADING_PEOPLE_LOOKING_PRODUCT = "SET_LOADING_PEOPLE_LOOKING_PRODUCT";
export const SET_PEOPLE_LOOKING_PRODUCT = "SET_PEOPLE_LOOKING_PRODUCT";
export const SET_PEOPLE_LOOKING_PRODUCT_ERROR = "SET_PEOPLE_LOOKING_PRODUCT_ERROR";

// slide banner
export const SET_SLIDE_BANNER_LOADING = "SET_SLIDE_BANNER_LOADING";
export const SET_SLIDE_BANNER = "SET_SLIDE_BANNER";
export const SET_SLIDE_BANNER_ERROR = "SET_SLIDE_BANNER_ERROR";

// cart
export const CART_LOADING = "CART_LOADING";
export const SET_CART_ITEM = "SET_CART_ITEM";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";

// order
export const SET_PAYMENT_INTENT = "SET_PAYMENT_INTENT";
export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_LOADING = "SET_ORDER_LOADING";
export const SET_ORDER = "SET_ORDER";
export const SET_ORDER_ITEM = "SET_ORDER_ITEM";

// Review
export const SET_REVIEW = "SET_REVIEW";
export const EMPTY_REVIEW_PAGE = "EMPTY_REVIEW_PAGE";
export const PERCENT_STAR_LOADING = "PERCENT_STAR_LOADING";
export const SET_PERCENT_STAR = "SET_PERCENT_STAR";